apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artifacts.name" . }}-config
data:
  nginx.server.conf: |
    {{- if .Values.general.internal_tls.enabled }}
    listen 8080 default_server ssl;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_certificate     /cert/tls.crt;
    ssl_certificate_key /cert/tls.key;
    {{- else }}
    listen 8080 default_server;
    {{- end }}
    server_name _;

    ## Headers
    proxy_set_header X-Request-ID      $req_id;

  nginx.http.conf: |
    ## Logging settings
    error_log /var/log/nginx/error.log {{ .Values.deployments.artifacts.loglevel }};
    {{- if .Values.deployments.artifacts.useJsonLogFormat }}
    log_format json escape=json '{'
        '"time_local":"$time_local",'
        '"remote_addr":"$remote_addr",'
        '"remote_user":"$remote_user",'
        '"request":"$request",'
        '"request_id":"$req_id",'
        '"status":$status,'
        '"body_bytes_sent":$body_bytes_sent,'
        '"request_length":$request_length,'
        '"request_time":$request_time,'
        '"http_referer":"$http_referer",'
        '"http_user_agent":"$http_user_agent",'
        '"http_range":"$http_range",'
        '"sent_http_content_range":"$sent_http_content_range",'
        '"content_type":"$content_type",'
        '"ssl_protocol":"$ssl_protocol",'
        '"ssl_cipher":"$ssl_cipher",'
    '}';                      
    access_log /var/log/nginx/access.log json;                  
    {{- else }}    
    log_format main '$remote_addr - $remote_user [$time_local] '
                          '"$request" $req_id $status $body_bytes_sent '
                          '"$http_referer" "$http_user_agent" '
                          '"$http_range" "$sent_http_content_range" '
                          '$request_time $request_length '
                          '"$content_type" "$ssl_protocol" "$ssl_cipher" ';
    access_log /var/log/nginx/access.log main;
    {{- end }}
    
    # Map set generated request_id if header not exists
    map $http_x_request_id $req_id {
        ""        $request_id;
        default   $http_x_request_id;
    }
