apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artifacts.name" . }}-config
data:
  nginx.server.conf: |
    {{- if .Values.general.internal_tls.enabled }}
    listen 8080 default_server ssl;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_certificate     /cert/tls.crt;
    ssl_certificate_key /cert/tls.key;
    {{- else }}
    listen 8080 default_server;
    {{- end }}
    server_name _;
  nginx.http.conf: |
    {{- if .Values.deployments.artifacts.useJsonLogFormat }}
    log_format json '{"time": "$time_iso8601", "remote_addr": "$remote_addr", "x_request_id": "$req_id",
                      "x_forwarded_for": "$http_x_forwarded_for", "bytes_sent": $bytes_sent,
                      "request_time": $request_time, "status": $status, "path": "$uri", "request_query": "$args",
                      "request_length": $request_length, "method": "$request_method", "http_referrer":"$http_referer",
                      "http_user_agent": "$http_user_agent", "upstream_status": "$upstream_status",
                      "upstream_response_time": "$upstream_response_time"}';
    access_log /var/log/nginx/access.log json;                  
    {{- else }}    
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for" "$req_id" '
                    '"$upstream_status" "$upstream_response_time"';
    access_log /var/log/nginx/access.log main;
    {{- end }}
