apiVersion: v1
kind: Service
metadata:
  name: {{ include "artifacts.name" . }}
  {{- with .Values.deployments.artifacts.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.deployments.artifacts.service.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ include "artifacts.name" . }}
