{{- if and .Values.serviceAccount.create .Values.general.system_diagnostics_k8s_api.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lightrun-be.name" . }}-sysdiag-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "lightrun-be.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "lightrun-be.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "lightrun-be.name" . }}-sysdiag-role
  namespace: {{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
