{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lightrun-sysdiag-role
rules:
  # Core API Resources
  - apiGroups: [""]
    resources:
      - namespaces
      - nodes
      - pods
      - services
      - configmaps
      - persistentvolumes
      - persistentvolumeclaims
      - serviceaccounts
      - events
    verbs:
      - get
      - list

  # Apps API Resources (Workloads)
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs:
      - get
      - list

  # Batch API Resources (Jobs)
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list

  # Storage API Resources
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs:
      - get
      - list

  # RBAC API Resources
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list

  # Networking API Resources
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - get
      - list

  # Non-Resource URLs for API server information
  - nonResourceURLs:
      - "/version"
      - "/api/v1"
      - "/apis"
    verbs:
      - get
{{- end }}
