{{- if and .Values.serviceAccount.create .Values.general.system_diagnostics_k8s_api.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lightrun-be.name" . }}-sysdiag-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "lightrun-be.name" . }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - persistentvolumeclaims
      - endpoints
      - resourcequotas
      - limitranges
      - events
    verbs:
      - get
      - list

  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs:
      - get
      - list

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - list

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - get
      - list
{{- end }}
