{{- if or .Values.serviceAccount.create .Values.system_diagnostics.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ include "lightrun-be.name" . }}
  name: {{ template "lightrun-be.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ or .Values.serviceAccount.automountServiceAccountToken .Values.system_diagnostics.enabled }}
{{- end }}
