{{ if and (not .Values.general.openshift) (not .Values.general.router.enabled) }}

{{ if .Values.general.ingress_controller }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.clients.name" . }}
  {{- with .Values.ingress_clients.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- if and (contains "nginx" $.Values.general.ingress_class_name)  $.Values.general.internal_tls.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.general.ingress_class_name }}
  tls:
    - hosts:
        - {{ .Values.general.lightrun_endpoint }}
      secretName: {{ include "secrets.certificate.name" . }}
  rules:
    - host: {{ .Values.general.lightrun_endpoint }}
      http:
        paths:
        - backend:
            service:
              name: {{ include "lightrun-keycloak.name" . }}
              port:
                number: 8080
          path: /auth
          pathType: Prefix
        - backend:
            service:
              name: {{ include "lightrun-fe.name" . }}
              port:
                number: 8080
          path: /device
          pathType: Prefix
        - backend:
            service:
              name: {{ include "lightrun-fe.name" . }}
              port:
                number: 8080
          path: /company
          pathType: Prefix
        - backend:
            service:
              name: {{ include "lightrun-fe.name" . }}
              port:
                number: 8080
          path: /app
          pathType: Prefix
        - backend:
            service:
              name: {{ include "lightrun-fe.name" . }}
              port:
                number: 8080
          path: /content
          pathType: Prefix
        - backend:
            service:
              name: {{ include "lightrun-fe.name" . }}
              port:
                number:
                  8080
          path: /
          pathType: Exact
        - backend:
            service:
              name: {{ include "lightrun-be.name" . }}
              port:
                number:
                  8080
          path: /
          pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.agents.name" . }}
  {{- with .Values.ingress_agents.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- if and (contains "nginx" $.Values.general.ingress_class_name)  $.Values.general.internal_tls.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.general.ingress_class_name }}
  rules:
    - host: {{ .Values.general.lightrun_endpoint }}
      http:
        paths:
        - backend:
            service:
              name: {{ include "lightrun-be.name" . }}
              port:
                number:
                  8080
          path: /debuggees
          pathType: Prefix
---
# This ingress used for blocking /auth/admin from open the world and allowing it only from the certain IPs
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.keycloak.name" . }}
  {{- with .Values.ingress_keycloak_admin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- if and (contains "nginx" $.Values.general.ingress_class_name)  $.Values.general.internal_tls.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.general.ingress_class_name }}
  rules:
    - host: {{ .Values.general.lightrun_endpoint }}
      http:
        paths:
        - backend:
            service:
              name: {{ include "lightrun-keycloak.name" . }}
              port:
                number: 8080
          path: /auth/
          pathType: Exact
        - backend:
            service:
              name: {{ include "lightrun-keycloak.name" . }}
              port:
                number: 8080
          path: /auth/realms/master
          pathType: Prefix
        - backend:
            service:
              name: {{ include "lightrun-keycloak.name" . }}
              port:
                number: 8080
          path: /auth/admin
          pathType: Prefix
        - backend:
            service:
              name: {{ include "lightrun-keycloak.name" . }}
              port:
                number: 8080
          path: /auth/realms/lightrun/internal
          pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.metrics.name" . }}-metrics
  {{- with .Values.ingress_metrics.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.general.lightrun_endpoint }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "lightrun-be.name" . }}
                port:
                  number:
                    8080
            path: /management/prometheus
            pathType: Exact
{{ end }}

{{ end }}
