apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightrun-keycloak.name" . }}
  {{ with .Values.deployments.keycloak.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
  {{ with .Values.deployments.keycloak.service.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 9080
      protocol: TCP
      name: keycloak
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: mgmt      
  selector:
    app: {{ include "lightrun-keycloak.name" . }}

{{- if .Values.deployments.keycloak.clusterMode }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightrun-keycloak.name" . }}-headless
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 7800
      targetPort: 7800
      protocol: TCP
      name: kc-cluster
  selector:
    app: {{ include "lightrun-keycloak.name" . }}

{{- end }}
