{{ if and .Values.general.mq.enabled .Values.general.mq.local -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ include "lightrun-mq.name" . }}
  name: {{ template "lightrun-mq.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{ end}}