{{ if ( include "secrets.deploy_secrets" . ) }}
{{ if not .Values.certificate.existing_cert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.certificate.name" . }}
data:
  tls.crt: {{ .Values.certificate.tls.crt }}
  tls.key: {{ .Values.certificate.tls.key }}
type: kubernetes.io/tls
{{ end }}
---
{{ if .Values.secrets.defaults.dockerhub_config }}
{{ if not .Values.secrets.defaults.dockerhub_config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.dockerhub.name" . }}
data:
  .dockerconfigjson: {{ .Values.secrets.defaults.dockerhub_config.configContent }}
type: kubernetes.io/dockerconfigjson
---
{{ end }}
{{ end }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "secrets.backend.name" . }}
type: Opaque
stringData:
  # Mandatory fields
  SPRING_SECURITY_KEYCLOAK_CLI_PASSWORD: {{ .Values.secrets.keycloak.password | quote }}
  SPRING_MAIL_PASSWORD: {{ .Values.secrets.defaults.mail_password | quote }}
  SPRING_FLYWAY_PASSWORD: {{ .Values.secrets.db.password | quote }}
  SPRING_FLYWAY_USER: {{ .Values.secrets.db.user | quote  }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.db.user | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.db.password | quote }}
  KEYSTORE_PASSWORD: {{ .Values.secrets.defaults.keystore_password | quote }}
  LICENSE_CONTENT: {{ .Values.secrets.license.content | quote }}
  LICENSE_SIGNATURE: {{ .Values.secrets.license.signature | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .Values.secrets.mq.user | default "" | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.secrets.mq.password | default "" | quote }}
  {{ include "secrets.encryption-key-name" . }}: {{include "secrets.encryption-key" . }}
  
  # Optional fields
  {{- if .Values.secrets.defaults.datadog_api_key }}
  INTEGRATIONS_DATADOG_APIKEY: {{ .Values.secrets.defaults.datadog_api_key | quote }}
  {{- end }}
  {{- if .Values.secrets.defaults.google_sso.client_id }}
  SPRING_SECURITY_GOOGLE_CLIENT-ID: {{ .Values.secrets.defaults.google_sso.client_id | quote }}
  {{- end }}
  {{- if .Values.secrets.defaults.google_sso.client_secret }}
  SPRING_SECURITY_GOOGLE_CLIENT-SECRET: {{ .Values.secrets.defaults.google_sso.client_secret | quote }}
  {{- end }}
  {{- if .Values.secrets.defaults.mixpanel_token }}
  TRACKING_MIXPANEL_TOKEN: {{ .Values.secrets.defaults.mixpanel_token | quote }}
  {{- end }}
  {{- if .Values.secrets.defaults.lightrun_initial_sys_api_key }}
  LIGHTRUN_INITIAL_SYS_API_KEY: {{ .Values.secrets.defaults.lightrun_initial_sys_api_key | quote }}
  {{- end }}
  {{- if .Values.secrets.redis.password }}
  SPRING_REDIS_PASSWORD: {{ .Values.secrets.redis.password | quote }}
  {{- end }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "secrets.keycloak.name" . }}
type: Opaque
stringData:
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: {{ .Values.secrets.keycloak.password | quote }}
  DB_USER: {{ .Values.secrets.db.user | quote }}
  DB_PASSWORD: {{ .Values.secrets.db.password | quote}}
{{ end }}
