{{ if and (not .Values.general.ingress_controller) (not .Values.general.router.enabled) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.name" . }}
  {{ with .Values.general.nginx_svc.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: {{ .Values.deployments.standalone_nginx.ports.https }}
    name: https
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.deployments.standalone_nginx.ports.http }}
    name: http
  selector:
    app: {{ include "nginx.name" . }}
  type: {{ .Values.general.nginx_svc.type }}


{{ end }}
