{{- if and .Values.serviceAccount.create .Values.general.data_streamer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ include "data_streamer.name" . }}
  name: {{ template "data_streamer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
