{{ if and .Values.general.openshift (not .Values.general.router.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "lightrun-fe.name" . }}-config
data:
  default.conf: |
    upstream backend {
      server {{ include "lightrun-be.name" . }}:8080;
    }

    upstream keycloak {
      server {{ include "lightrun-keycloak.name" . }}:8080;
    }

    server {
  
      listen 8080 default_server;
      # large_client_header_buffers 4 16k;
      server_name _;

      root /usr/share/nginx/html;
      index index.html index.htm;


      location = / {
        gzip_static on;
        index index.html
        try_files $uri $uri/ @index;
        error_page 404 = @index;
        log_not_found off;
      }

      location /app {
        gzip_static on;
        index index.html
        try_files $uri $uri/ @index;
        error_page 404 = @index;
        log_not_found off;
      }

      location /device {
        gzip_static on;
        index index.html
        try_files $uri $uri/ @index;
        error_page 404 = @index;
        log_not_found off;
      }

      location /company {
        gzip_static on;
        index index.html
        try_files $uri $uri/ @index;
        error_page 404 = @index;
        log_not_found off;
      }

      location /content {
        gzip_static on;
        index index.html
        try_files $uri $uri/ @index;
        error_page 404 = @index;
        log_not_found off;
      }


      location / {
        proxy_pass http://backend$request_uri;
        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;
      }

      location /socket {

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://backend$request_uri;
        proxy_ssl_verify              off;

        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;
      }

      location /auth/ {
        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;
        proxy_pass http://keycloak$request_uri;
      }

      location = /index.html {
        add_header Cache-Control 'no-store, no-cache, max-age=0';
      }

      location @index {
        add_header Cache-Control 'no-store, no-cache, max-age=0';
        try_files /index.html =404;
      }

    }

{{ end }}
