{{ if and .Values.general.openshift (not .Values.general.router.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.clients.name" . }}
spec:
  tls:
    # If you want to use default openshift domain fo lightrun application, for example: 
    # https://lightrun.apps.test.o5mj.p1.openshiftapps.com/
    {{ if .Values.general.openshift_embeded_hostname }}
    - {}
    {{ else }}
    - hosts:
      - {{ .Values.general.lightrun_endpoint }}
      secretName: {{ include "secrets.certificate.name" . }}
    {{ end }}
  rules:
    - host: {{ .Values.general.lightrun_endpoint }}
      http:
        paths:
        - backend:
            service:
              name: {{ include "lightrun-fe.name" . }}
              port:
                number:
                  8080
          path: /
          pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.agents.name" . }}
spec:
  tls:
    # If you want to use default openshift domain fo lightrun application, for example: 
    # https://lightrun.apps.test.o5mj.p1.openshiftapps.com/
    {{ if .Values.general.openshift_embeded_hostname }}
    - {}
    {{ else }}
    - hosts:
      - {{ .Values.general.lightrun_endpoint }}
      secretName: {{ include "secrets.certificate.name" . }}
    {{ end }}
  rules:
    - host: {{ .Values.general.lightrun_endpoint }}
      http:
        paths:
        - backend:
            service:
              name: {{ include "lightrun-be.name" . }}
              port:
                number:
                  8080
          path: /debuggees
          pathType: Prefix
          
{{ end }}
