{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ include "lightrun-be.name" . }}
  name: {{ template "lightrun-be.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ or .Values.serviceAccount.automountServiceAccountToken .Values.general.system_diagnostics_k8s_api.enabled }}
{{- end }}
