apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightrun-fe.name" . }}
  {{ with .Values.deployments.frontend.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
  {{ with .Values.deployments.frontend.service.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "lightrun-fe.name" . }}
