{{ if .Values.deployments.backend.hpa.enabled }}
{{- if .Values.deployments.backend.hpa.apiVersion }}
apiVersion: {{ .Values.deployments.backend.hpa.apiVersion }}
{{- else }}
{{- if semverCompare ">=1.23.0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lightrun-be.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lightrun-be.name" . }}
  minReplicas: {{ .Values.deployments.backend.replicas }}
  maxReplicas: {{ .Values.deployments.backend.hpa.maxReplicas }}
  metrics:
  {{- if .Values.deployments.backend.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.deployments.backend.hpa.cpu }}
  {{- end }}
  {{- if .Values.deployments.backend.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.deployments.backend.hpa.memory }}
  {{- end }}
{{ end }}
{{ if .Values.deployments.frontend.hpa.enabled }}
---
{{- if .Values.deployments.frontend.hpa.apiVersion }}
apiVersion: {{ .Values.deployments.frontend.hpa.apiVersion }}
{{- else }}
{{- if semverCompare ">=1.23.0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lightrun-fe.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lightrun-fe.name" . }}
  minReplicas:  {{ .Values.deployments.frontend.replicas }}
  maxReplicas:  {{ .Values.deployments.frontend.hpa.maxReplicas }}
  metrics:
  {{- if .Values.deployments.frontend.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.deployments.frontend.hpa.cpu }}
  {{- end }}
  {{- if .Values.deployments.frontend.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.deployments.frontend.hpa.memory }}
  {{- end }}
{{ end }}
---
{{ if .Values.deployments.router.hpa.enabled }}
{{- if .Values.deployments.router.hpa.apiVersion }}
apiVersion: {{ .Values.deployments.router.hpa.apiVersion }}
{{- else }}
{{- if semverCompare ">=1.23.0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "router.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "router.name" . }}
  minReplicas:  {{ .Values.deployments.router.replicas }}
  maxReplicas:  {{ .Values.deployments.router.hpa.maxReplicas }}
  metrics:
  {{- if .Values.deployments.router.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.deployments.router.hpa.cpu }}
  {{- end }}
  {{- if .Values.deployments.router.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.deployments.router.hpa.memory }}
  {{- end }}
{{ end }}


