{{ if and .Values.general.internal_tls.enabled (eq .Values.general.internal_tls.certificates.source "generate_self_signed_certificates") -}}
{{ range (list (include "lightrun-fe.name" $ ) (include "lightrun-keycloak.name" $ ) (include "lightrun-redis.name" $ ) (include "lightrun-mq.name" $ ) (include "data_streamer.name" $ ) (include "artifacts.name" $ ) )}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ . }}-cert
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "internal-tls.gen-crt" (list $ . )) | indent 2 }}
---
{{- end }}
{{- end }}
