{{- if include "runtime_collector.clickhouse.internalTls.certEnabled" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "runtime_collector.clickhouse.name" . }}-ssl-config
  labels:
    app: {{ include "runtime_collector.clickhouse.name" . }}
data:
  ssl-config.xml: |
    <clickhouse>
        <http_port remove="1"/>
        <https_port>{{ .Values.runtime_collector.clickhouse.local.httpPort }}</https_port>
        <tcp_port remove="1"/>
        <tcp_port_secure>{{ .Values.runtime_collector.clickhouse.local.nativePort }}</tcp_port_secure>
        <openSSL>
            <server>
                <certificateFile>/tmp/certs/tls.crt</certificateFile>
                <privateKeyFile>/tmp/certs/tls.key</privateKeyFile>
                <verificationMode>none</verificationMode>
            </server>
        </openSSL>
    </clickhouse>
{{- end }}
