{{- if and .Values.runtime_collector.enabled .Values.runtime_collector.clickhouse.local.enabled .Values.runtime_collector.clickhouse.local.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "runtime_collector.clickhouse.name" . }}-data
  labels:
    app: {{ include "runtime_collector.clickhouse.name" . }}
spec:
  accessModes:
    - {{ .Values.runtime_collector.clickhouse.local.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.runtime_collector.clickhouse.local.persistence.size }}
  storageClassName: {{ .Values.runtime_collector.clickhouse.local.persistence.storageClassName | quote }}
{{- end }}
