{{- if and .Values.serviceAccount.create .Values.runtime_collector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ include "runtime_collector.name" . }}
  name: {{ template "runtime_collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
